name: XyForgeCrafting
version: '1.0.3'
main: org.xyplugin.xyforgecrafting.XyForgeCraftingPlugin
api-version: '1.12'
author: XyPlugins
description: Xy series transactional forging system for Paper/Spigot 1.12.2 only.
depend: [XyCore, XyItems]
softdepend: [XySoulSpace]

commands:
  xyfc:
    description: XyForgeCrafting main command
    usage: /xyfc <open|get|give|list|reload|help>
    aliases: [xyforge, xyforgecrafting]

permissions:
  xyforgecrafting.use:
    description: Allows opening and using the forge.
    default: true
  xyforgecrafting.give:
    description: Allows giving signed forge blueprints.
    default: op
  xyforgecrafting.get:
    description: Allows players to obtain signed forge blueprints for themselves.
    default: op
  xyforgecrafting.list:
    description: Allows listing loaded recipes.
    default: op
  xyforgecrafting.reload:
    description: Allows safely reloading forge configuration.
    default: op
